// examples/with-react-vite/src/App.jsx
import ThemePlayer from './components/ThemePlayer.jsx';
import TimeLine from './components/TimeLine.jsx';

export default function App() {
  return (
    <div
      style={{
        fontFamily: 'Avenir, Helvetica, Arial, sans-serif',
        WebkitFontSmoothing: 'antialiased',
        MozOsxFontSmoothing: 'grayscale',
        textAlign: 'center',
        color: '#2c3e50',
        padding: '24px',
      }}
    >
      <h1>@ezuikit/player-theme · React + Vite</h1>
      <TimeLine />
      <ThemePlayer />
    </div>
  );
}

// examples/with-vue2.5.17/src/App.vue
<template>
  <div id="app">
    <TimeLine />
    <Theme />
  </div>
</template>

<script>
import TimeLine from './components/index.vue';
import Theme from './components/theme.vue';

export default {
  name: 'app',
  components: {
    TimeLine,
    Theme
  },
};
</script>
<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
  height: 150vh;
}
</style>
